name: Tribu
main: graindcafe.tribu.Tribu
version: 0.4.1.1000
commands:
    tribu:
        description: start,stop, join, leave, the game, create, save, load, levels. 
        usage: /tribu enter | leave | vote <1|2>
    zspawn:
        description: creates a zombie spawnpoint at the current location. Use [jump] <name> to jump to the spawn
        usage: /zspawn (( set | remove | jump ) <name> ) | list
    dspawn:
        description: sets the death spawnpoint. Use [jump] to jump to the spawn
        usage: /dspawn [jump]
    ispawn:
        description: sets the initial spawnpoint. Use [jump] to jump to the spawn
        usage: /ispawn [jump]
    